version: '3.5'  

services: 
    front: 
      image: app_front 
      build: .
      ports: 
        - 5000:5000
    back:
      image: app_backend
      build: .
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_HOST=postgres
    redis:
      image: redis
      restart: unless-stopped
    postgres:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=password
      
