version: '3'  

services: 
    front: 
      image: app_front 
      ports: 
        - 5000:5000 
    back:
      image: app_backend
      ports:
        - 8000:8000
      environment:
        - REDIS=redis
    redis:
      image: redis
      restart: unless-stopped
    
