  version: '3.5'

  services:
    frontend:
      image: ml-front 
      build : .
      ports:
        - 3000:3000
    backend:
      image: ml-back
      build: . 
      ports:
        - 5000:5000
      volumes:
        - ./model:/src/model
    training:
      image: ml-training
      build: .
      volumes:
       - ./model:/src/model
       - ./data:/src/imgs
