version: '3.5'

services:
    frontend:
      image: app_front
      build: .
      ports:
        - 5000:5000
      container_name: frontend
    backend:
      image: app_backend
      build: .
      ports:
        - 8000:8000
      container_name: backend
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_HOST=postgres
    redis:
      image: redis
      restart: unless-stopped
    postgres:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=password
      volumes:
        - ./data:/var/lib/postgresql/data
    proxy: 
      image: jwilder/nginx-proxy 
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80       

volumes:
    data:
