version: '3.5'

services:
    front:
      image: app_front
      build: .
      container_name: front
    back:
      image: app_backend
      build: .
      container_name: back
      environment:
        - REDIS=redis
        - DB_USERNAME=postgres
        - DB_PASSWORD=password
        - DB_HOST=postgres
    redis:
      image: redis
      restart: unless-stopped
    postgres:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=password
    proxy: 
      image: jwilder/nginx-proxy 
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80       
